packages:
  - apps/*
  - packages/*

overrides:
  deepmerge-ts@7.1.5: 8.0.2
  mariadb@3.4.5: 3.5.4
  mysql2@3.15.3: 3.24.4

allowBuilds:
  "@prisma/engines@7.10.0": true
  esbuild@0.28.2: true
  prisma@7.10.0: true

minimumReleaseAgeExclude:
  - zod@4.6.4
